server:
  port: 8180
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study-app?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  resources:
    static-locations: ["classpath:/static/", "classpath:/images"]
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: org.zongf.wx.power.nation.po